# Site settings
title: Ju Xu
description:
  en: "This is an academic website for Ju Xu to share his experiences, projects, publications and so on."
  cn: "这是徐举的个人学术主页，用于分享他的个人经历，项目，学术论文等。"
keywords:
  en: "Ju Xu,Publications,Machine Learning,Deep Learning, autoML."
  cn: "徐举,学术论文,机器学习,深度学习,自动机器学习。"
background: /images/background/background-aurora.jpg
deep_background: /images/background/background-aurora.jpg

baseurl: ""
# the subpath of your site, e.g. /blog/
url: "https://xujinfan.github.io"
# the base hostname & protocol for your sit

# Paginationœ
paginate: 6
paginate_path: "/posts/page/:num/"

# Build settings
markdown: kramdown

# permalink setting
permalink: pretty
# highlighter: rouge
highlighter: rouge

# Social media link for the site
social:
  twitter:    ''
  github:     xujinfan
  facebook:   profile.php?id=100028355807550
  linkedin:   举-徐-09b4b0167/
  rss:        /feed.xml

# customized document resources
collections:
  projects:
    output: true

scss:
  sass_dir: _scss
  style: :compressed

gems:
  ['jekyll-paginate', 'jekyll/scholar', 'jekyll-sitemap']
